language: node_js
node_js:
  - "7.8"

branches:
  only:
    - master

install:
  - npm install

before_script:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN